---
## Show all KEY VALUE pairs for the environment

- name: TESTING LOOPS
  hosts: all
  become: yes

  tasks:
  - name: PARSE OVER THE ENVIRONMENT FACTS
    debug: msg={{item.key}}={{item.value}}
    with_dict: ansible_env

  - name: Do untill something
    shell: echo hello
    register: output
    delay: 5
    untill: output.stdout.find('hello') != 5

