---
- name: ANSIBLE VARIABLES
  hosts: all
  become: yes


  tasks:
  - name: GET INFO...
## Using SHELL-REGISTER-DEBUG
    shell: uname -a
    register: OS
  - debug: msg="THE OS IS {{OS.stdout}}"

## USING FACTS 
#  Using local facts decleared in /etc/ansible/facts.d/example.fact 
#  - debug: var=ansible_local

##Using Just debug
  - debug: var=ansible_distribution
  - debug: var=ansible_bios_date
  - debug: var=ansible_memory_mb
  - debug: var=ansible_python_version

 
## Decleare vars in same playbook or directory, one level up.









