---
- name: install and configure mariadb
  hosts: all
  become: yes

  vars_files:
  - maria_vars.yaml  

  tasks:
  - name: install mariadb
    yum: name=mariadb state=latest

  - name: create mysql conf file
    template: src=my.cnf.j2 dest=/etc/my.cnf
    notify: restart mariadb

  - name: CREATE USERS AND GROUPS
    user: 
      name: mysql
      comment: "MYSQL user"	 


  - name: create mariadb log file
    file: path={{log_path}}/mysqld.log state=touch owner=mysql group=mysql mode=0775
    
  - name: start mariadb service
    service: name=mariadb state=started enabled=yes

  - name:  STATUS mariadb service
    shell: service mysqld status


  handlers:
  - name: restart mariadb
    service: name=mariadb state=restarted
